### PR TITLE
Updated Dockerfile

### PR DESCRIPTION
**Pull request by iAmG-r00t**
Hey, so I have updated the dockerfile as you had requested. #16 , kindly review it and advice.

### CODE REVIEW

**Comment by codekitchen** [comment]
Cool thanks! One thing though, since this Dockerfile will be run directly from within the repo there's no need to download the code using curl etc... you can just grab the code directly using the COPY command that was in there originally. That way we can build for any given commit at any time, but just checking out the correct commit.

**Comment by iAmG-r00t** [comment]
Ideally my plan was to have a way to spin up  the docker container without
the  need to git clone the whole repository.

/gr00t

"La vie c’est comme la bicyclette : quand on arrête de pédaler on tombe."

**Comment by codekitchen** [comment]
hm I think there's still some confusion here -- ultimately I'm going to set this up as a public docker image that is auto-built on hub.docker.com, so you won't need to build it locally at all. You'll just use `docker pull codekitchen/pipeline:latest` etc.

If you did want to extend that container, you'd do that by using `FROM codekitchen/pipeline` at the top of a new Dockerfile, so you'd still not have to clone the repo.

**Comment by iAmG-r00t** [comment]
Sure that is a good idea.

**Pull request closed without merging**
