### PR TITLE
Dockerfile Update

### PR DESCRIPTION
**Pull request by iAmG-r00t**
Hi, so I wasn't able to find a way to add a snap package, but I found a way to install it to a docker container. I saw you have a dockerfile but I never liked the fact that I have to gitclone the repo so as to use the docker container. So I managed to script something up that doesn't require a user to git clone the repo and also updated the readme for the users to be able to add an alias that will automatically mount the directory it's being called from and use the `pipeline` shell command as if they had installed it to the operating system itself.

This pull request solves the following issues #15 #6 . Thanks alot for your tool.

Before you merge please do edit the following below section ...
... from this:

```sh
# Get the dockerfile2 file
curl -L https://raw.githubusercontent.com/iAmG-r00t/pipeline/master/Dockerfile2 -o pipeline-dockerfile

# Build a powerline image
docker build -t pipeline:latest -f pipeline-dockerfile .

# Alias
alias pipeline='docker run -it --rm --name pipeline -v `pwd`:/root pipeline:latest' 
``` 

... to this:

```sh
# Get the dockerfile2 file
curl -L https://raw.githubusercontent.com/codekitchen/pipeline/master/Dockerfile2 -o pipeline-dockerfile

# Build a powerline image
docker build -t pipeline:latest -f pipeline-dockerfile .

# Alias
alias pipeline='docker run -it --rm --name pipeline -v `pwd`:/root pipeline:latest' 
```

### CODE REVIEW

**Comment by codekitchen** [comment]
Thanks! I could have given you some more direction for a Docker-based install, sorry. I have a lot of Docker experience but I honestly never considered releasing a docker image for `pipeline`, as it wouldn't work too well for a lot of my use cases -- I usually want to use other shell commands installed on my system, such as `jq` for parsing json, and I think it'd be difficult to come up with a `pipeline` Docker container that has all the shell commands I might want to use pre-installed.

But if this works well for your use cases, I think it'd be great to publish a docker image. I'd rather push it up to https://hub.docker.com as a public image, rather than make people build it themselves locally. We can link it up with github so that it automatically builds a new image whenever I push a new version.

In order to do that, I think we just need to adapt the current `Dockerfile` a bit rather than add a 2nd one, and then only the repo owner can do the setup on hub.docker.com so I can take care of that part.

I do think it might make sense to use ubuntu or debian or some other similar image as the base, rather than alpine, since I will probably end up wanting to pre-install a lot of utlities like `jq` in the Dockerfile, and some shell utilities are difficult to install on a minimal alpine container.

What do you think?

**Comment by iAmG-r00t** [comment]
I use `jq` most times with `curl`, s using it with `pipeline` wouldn't make sense for me, but I wanted an effecient way to install `pipeline` without alot of process and I wanted a way to automate the installation process. So I thought having a docker image that is lightweight would be sufficient.

So on your suggestions I would say, you can think about it but the way you explained about having most tools in one docker container makes alot of sense. Question is how many utilities would one need to pre-install??

**Comment by codekitchen** [comment]
Yeah that's where docker feels like less of a good fit, I don't see how we could possibly ever install every utility that every person might want to use. But it feels like installing at least some basic set of utilities is better than nothing. I'll probably still look into a more standard apt package or something eventually.

[Here's a start to a Dockerfile](https://gist.github.com/codekitchen/185c2da91262374f85245afb77a7fc45) that uses the pattern of having separate build and run containers to keep size down. Something like that is probably a good direction to take. Then having that auto-built and hosted inside this repo will prevent people having to build it themselves, they can just `docker run codekitchen/pipeline` instead (wrapping it in that awesome alias you added)

By the way this PR includes some reformatting of the README that I'd rather avoid, it made a bunch of the sections bulleted lists for some reason?

**Comment by iAmG-r00t** [comment]
I can edit the bulleted list, Let me do so now.

**Comment by iAmG-r00t** [comment]
I have edited it, is it better ?? .... if it is remember to edit the following below section ...
... from this:

```sh
# Get the dockerfile2 file
curl -L https://raw.githubusercontent.com/iAmG-r00t/pipeline/master/Dockerfile2 -o pipeline-dockerfile

# Build a powerline image
docker build -t pipeline:latest -f pipeline-dockerfile .

# Alias
alias pipeline='docker run -it --rm --name pipeline -v `pwd`:/root pipeline:latest' 
```
... to this:

```sh
# Get the dockerfile2 file
curl -L https://raw.githubusercontent.com/codekitchen/pipeline/master/Dockerfile2 -o pipeline-dockerfile

# Build a powerline image
docker build -t pipeline:latest -f pipeline-dockerfile .

# Alias
alias pipeline='docker run -it --rm --name pipeline -v `pwd`:/root pipeline:latest' 
```

**Comment by codekitchen** [comment]
Cool thanks. But I still don't think it makes sense to provide these manual build instructions in the README when it'd be so easy to just provide a pre-built docker container instead. Are you interested in modifying the already-existing Dockerfile to set that up? If not I can probably do it myself sometime soon.

**Comment by iAmG-r00t** [comment]
Hey I can definitely edit the existing one, let me work on it.

"La vie c’est comme la bicyclette : quand on arrête de pédaler on tombe."

**Comment by iAmG-r00t** [comment]
Hey so I have managed to edit, will be closing this pull request and opening a new one with the Dockerfile updated.

**Pull request closed without merging**
